<?php

/**
 * This file was automatically generated by k8s/api-generator 0.12.0 for API version v1.29.6
 *
 * (c) Chad Sikorra <Chad.Sikorra@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace K8s\Api\Service\Coordination\v1;

use K8s\Api\Model\Api\Coordination\v1\Lease;
use K8s\Api\Model\Api\Coordination\v1\LeaseList;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\Status;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\WatchEvent;
use K8s\Core\Contract\ApiInterface;

class LeaseService
{
    /** @var ApiInterface */
    private $api;

    /** @var string|null */
    private $namespace;

    public function __construct(ApiInterface $api)
    {
        $this->api = $api;
    }

    public function useNamespace(string $namespace): self
    {
        $this->namespace = $namespace;

        return $this;
    }

    /**
     * List or watch objects of kind Lease
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#list-lease-v1-coordination-k8s-io
     */
    public function listCoordinationV1ForAllNamespaces(array $query = []): LeaseList
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = LeaseList::class;
        $uri = $this->api->makeUri(
            '/apis/coordination.k8s.io/v1/leases',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'list',
            $options
        );
    }

    /**
     * List or watch objects of kind Lease
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#list-lease-v1-coordination-k8s-io
     */
    public function listCoordinationV1Namespaced(array $query = []): LeaseList
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = LeaseList::class;
        $uri = $this->api->makeUri(
            '/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'list',
            $options
        );
    }

    /**
     * Delete collection of Lease
     *
     * Allowed query parameters:
     *   dryRun
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#delete-collection-lease-v1-coordination-k8s-io
     */
    public function deleteCoordinationV1CollectionNamespaced(array $query = []): Status
    {
        $options['query'] = $query;
        $options['method'] = 'delete';
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'deletecollection',
            $options
        );
    }

    /**
     * Create a Lease
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#create-lease-v1-coordination-k8s-io
     */
    public function createCoordinationV1Namespaced(Lease $lease, array $query = []): Lease
    {
        $options['query'] = $query;
        $options['method'] = 'post';
        $options['body'] = $lease;
        $options['model'] = Lease::class;
        $uri = $this->api->makeUri(
            '/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'post',
            $options
        );
    }

    /**
     * Read the specified Lease
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#read-lease-v1-coordination-k8s-io
     */
    public function readCoordinationV1Namespaced(string $name, array $query = []): Lease
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = Lease::class;
        $uri = $this->api->makeUri(
            '/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'get',
            $options
        );
    }

    /**
     * Delete a Lease
     *
     * Allowed query parameters:
     *   dryRun
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#delete-lease-v1-coordination-k8s-io
     */
    public function deleteCoordinationV1Namespaced(string $name, array $query = []): Status
    {
        $options['query'] = $query;
        $options['method'] = 'delete';
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'delete',
            $options
        );
    }

    /**
     * Partially update the specified Lease
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#patch-lease-v1-coordination-k8s-io
     */
    public function patchCoordinationV1Namespaced(string $name, array $query = []): Lease
    {
        $options['query'] = $query;
        $options['method'] = 'patch';
        $options['model'] = Lease::class;
        $uri = $this->api->makeUri(
            '/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'patch',
            $options
        );
    }

    /**
     * Replace the specified Lease
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#put-lease-v1-coordination-k8s-io
     */
    public function replaceCoordinationV1Namespaced(string $name, Lease $lease, array $query = []): Lease
    {
        $options['query'] = $query;
        $options['method'] = 'put';
        $options['body'] = $lease;
        $options['model'] = Lease::class;
        $uri = $this->api->makeUri(
            '/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'put',
            $options
        );
    }

    /**
     * Watch individual changes to a list of Lease. deprecated: use the 'watch' parameter with a list
     * operation instead.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#watchlist-lease-v1-coordination-k8s-io
     */
    public function watchCoordinationV1ListForAllNamespaces(array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/coordination.k8s.io/v1/watch/leases',
            [],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watchlist',
            $options
        );
    }

    /**
     * Watch individual changes to a list of Lease. deprecated: use the 'watch' parameter with a list
     * operation instead.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#watchlist-lease-v1-coordination-k8s-io
     */
    public function watchCoordinationV1NamespacedList(array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/coordination.k8s.io/v1/watch/namespaces/{namespace}/leases',
            [],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watchlist',
            $options
        );
    }

    /**
     * Watch changes to an object of kind Lease. deprecated: use the 'watch' parameter with a list
     * operation instead, filtered to a single item with the 'fieldSelector' parameter.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#watch-lease-v1-coordination-k8s-io
     */
    public function watchCoordinationV1Namespaced(string $name, array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/coordination.k8s.io/v1/watch/namespaces/{namespace}/leases/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watch',
            $options
        );
    }
}
