<?php

/**
 * This file was automatically generated by k8s/api-generator 0.12.0 for API version v1.28.12
 *
 * (c) Chad Sikorra <Chad.Sikorra@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace K8s\Api\Service\Networking\v1alpha1;

use K8s\Api\Model\Api\Networking\v1alpha1\ClusterCIDR;
use K8s\Api\Model\Api\Networking\v1alpha1\ClusterCIDRList;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\Status;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\WatchEvent;
use K8s\Core\Contract\ApiInterface;

class ClusterCIDRService
{
    /** @var ApiInterface */
    private $api;

    /** @var string|null */
    private $namespace;

    public function __construct(ApiInterface $api)
    {
        $this->api = $api;
    }

    public function useNamespace(string $namespace): self
    {
        $this->namespace = $namespace;

        return $this;
    }

    /**
     * List or watch objects of kind ClusterCIDR
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#list-clustercidr-v1alpha1-networking-k8s-io
     */
    public function listNetworkingV1alpha1(array $query = []): ClusterCIDRList
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = ClusterCIDRList::class;
        $uri = $this->api->makeUri(
            '/apis/networking.k8s.io/v1alpha1/clustercidrs',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'list',
            $options
        );
    }

    /**
     * Delete collection of ClusterCIDR
     *
     * Allowed query parameters:
     *   dryRun
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#delete-collection-clustercidr-v1alpha1-networking-k8s-io
     */
    public function deleteNetworkingV1alpha1Collection(array $query = []): Status
    {
        $options['query'] = $query;
        $options['method'] = 'delete';
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/apis/networking.k8s.io/v1alpha1/clustercidrs',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'deletecollection',
            $options
        );
    }

    /**
     * Create a ClusterCIDR
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#create-clustercidr-v1alpha1-networking-k8s-io
     */
    public function createNetworkingV1alpha1(ClusterCIDR $clusterCIDR, array $query = []): ClusterCIDR
    {
        $options['query'] = $query;
        $options['method'] = 'post';
        $options['body'] = $clusterCIDR;
        $options['model'] = ClusterCIDR::class;
        $uri = $this->api->makeUri(
            '/apis/networking.k8s.io/v1alpha1/clustercidrs',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'post',
            $options
        );
    }

    /**
     * Read the specified ClusterCIDR
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#read-clustercidr-v1alpha1-networking-k8s-io
     */
    public function readNetworkingV1alpha1(string $name, array $query = []): ClusterCIDR
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = ClusterCIDR::class;
        $uri = $this->api->makeUri(
            '/apis/networking.k8s.io/v1alpha1/clustercidrs/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'get',
            $options
        );
    }

    /**
     * Delete a ClusterCIDR
     *
     * Allowed query parameters:
     *   dryRun
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#delete-clustercidr-v1alpha1-networking-k8s-io
     */
    public function deleteNetworkingV1alpha1(string $name, array $query = []): Status
    {
        $options['query'] = $query;
        $options['method'] = 'delete';
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/apis/networking.k8s.io/v1alpha1/clustercidrs/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'delete',
            $options
        );
    }

    /**
     * Partially update the specified ClusterCIDR
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#patch-clustercidr-v1alpha1-networking-k8s-io
     */
    public function patchNetworkingV1alpha1(string $name, array $query = []): ClusterCIDR
    {
        $options['query'] = $query;
        $options['method'] = 'patch';
        $options['model'] = ClusterCIDR::class;
        $uri = $this->api->makeUri(
            '/apis/networking.k8s.io/v1alpha1/clustercidrs/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'patch',
            $options
        );
    }

    /**
     * Replace the specified ClusterCIDR
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#put-clustercidr-v1alpha1-networking-k8s-io
     */
    public function replaceNetworkingV1alpha1(string $name, ClusterCIDR $clusterCIDR, array $query = []): ClusterCIDR
    {
        $options['query'] = $query;
        $options['method'] = 'put';
        $options['body'] = $clusterCIDR;
        $options['model'] = ClusterCIDR::class;
        $uri = $this->api->makeUri(
            '/apis/networking.k8s.io/v1alpha1/clustercidrs/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'put',
            $options
        );
    }

    /**
     * Watch individual changes to a list of ClusterCIDR. deprecated: use the 'watch' parameter with a list
     * operation instead.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#watchlist-clustercidr-v1alpha1-networking-k8s-io
     */
    public function watchNetworkingV1alpha1List(array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/networking.k8s.io/v1alpha1/watch/clustercidrs',
            [],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watchlist',
            $options
        );
    }

    /**
     * Watch changes to an object of kind ClusterCIDR. deprecated: use the 'watch' parameter with a list
     * operation instead, filtered to a single item with the 'fieldSelector' parameter.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#watch-clustercidr-v1alpha1-networking-k8s-io
     */
    public function watchNetworkingV1alpha1(string $name, array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/networking.k8s.io/v1alpha1/watch/clustercidrs/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watch',
            $options
        );
    }
}
