<?php

/**
 * This file was automatically generated by k8s/api-generator 0.9.0 for API version v1.11.10
 *
 * (c) Chad Sikorra <Chad.Sikorra@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace K8s\Api\Service\Policy\v1beta1;

use K8s\Api\Model\Api\Policy\v1beta1\PodDisruptionBudget;
use K8s\Api\Model\Api\Policy\v1beta1\PodDisruptionBudgetList;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\DeleteOptions;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\Status;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\WatchEvent;
use K8s\Core\Contract\ApiInterface;
use K8s\Core\PatchInterface;

class PodDisruptionBudgetService
{
    /** @var ApiInterface */
    private $api;

    /** @var string|null */
    private $namespace;

    public function __construct(ApiInterface $api)
    {
        $this->api = $api;
    }

    public function useNamespace(string $namespace): self
    {
        $this->namespace = $namespace;

        return $this;
    }

    /**
     * List or watch objects of kind PodDisruptionBudget
     *
     * Allowed query parameters:
     *   continue
     *   fieldSelector
     *   includeUninitialized
     *   labelSelector
     *   limit
     *   resourceVersion
     *   timeoutSeconds
     *   watch
     *   pretty
     *
     * @param array $query
     * @param callable|object|null $handler
     */
    public function listNamespaced(array $query = [], $handler = null): ?PodDisruptionBudgetList
    {
        $options['query'] = $query;
        $options['handler'] = $handler;
        $options['model'] = PodDisruptionBudgetList::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/namespaces/{namespace}/poddisruptionbudgets',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'list',
            $options
        );
    }

    /**
     * Delete collection of PodDisruptionBudget
     *
     * Allowed query parameters:
     *   continue
     *   fieldSelector
     *   includeUninitialized
     *   labelSelector
     *   limit
     *   resourceVersion
     *   timeoutSeconds
     *   watch
     *   pretty
     *
     * @param array $query
     * @param callable|object|null $handler
     */
    public function deleteCollectionNamespaced(array $query = [], $handler = null): ?Status
    {
        $options['query'] = $query;
        $options['handler'] = $handler;
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/namespaces/{namespace}/poddisruptionbudgets',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'deletecollection',
            $options
        );
    }

    /**
     * Create a PodDisruptionBudget
     *
     * Allowed query parameters:
     *   pretty
     *
     * @param array $query
     */
    public function createNamespaced(PodDisruptionBudget $podDisruptionBudget, array $query = []): PodDisruptionBudget
    {
        $options['query'] = $query;
        $options['body'] = $podDisruptionBudget;
        $options['model'] = PodDisruptionBudget::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/namespaces/{namespace}/poddisruptionbudgets',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'post',
            $options
        );
    }

    /**
     * Read the specified PodDisruptionBudget
     *
     * Allowed query parameters:
     *   exact
     *   export
     *   pretty
     *
     * @param array $query
     */
    public function readNamespaced(string $name, array $query = []): PodDisruptionBudget
    {
        $options['query'] = $query;
        $options['model'] = PodDisruptionBudget::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/namespaces/{namespace}/poddisruptionbudgets/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'get',
            $options
        );
    }

    /**
     * Delete a PodDisruptionBudget
     *
     * Allowed query parameters:
     *   gracePeriodSeconds
     *   orphanDependents
     *   propagationPolicy
     *   pretty
     *
     * @param array $query
     */
    public function deleteNamespaced(string $name, DeleteOptions $deleteOptions, array $query = []): Status
    {
        $options['query'] = $query;
        $options['body'] = $deleteOptions;
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/namespaces/{namespace}/poddisruptionbudgets/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'delete',
            $options
        );
    }

    /**
     * Partially update the specified PodDisruptionBudget
     *
     * Allowed query parameters:
     *   pretty
     *
     * @param array $query
     */
    public function patchNamespaced(string $name, PatchInterface $patch, array $query = []): PodDisruptionBudget
    {
        $options['query'] = $query;
        $options['body'] = $patch;
        $options['model'] = PodDisruptionBudget::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/namespaces/{namespace}/poddisruptionbudgets/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'patch',
            $options
        );
    }

    /**
     * Replace the specified PodDisruptionBudget
     *
     * Allowed query parameters:
     *   pretty
     *
     * @param array $query
     */
    public function replaceNamespaced(string $name, PodDisruptionBudget $podDisruptionBudget, array $query = []): PodDisruptionBudget
    {
        $options['query'] = $query;
        $options['body'] = $podDisruptionBudget;
        $options['model'] = PodDisruptionBudget::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/namespaces/{namespace}/poddisruptionbudgets/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'put',
            $options
        );
    }

    /**
     * Read status of the specified PodDisruptionBudget
     *
     * Allowed query parameters:
     *   pretty
     *
     * @param array $query
     */
    public function readNamespacedStatus(string $name, array $query = []): PodDisruptionBudget
    {
        $options['query'] = $query;
        $options['model'] = PodDisruptionBudget::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/namespaces/{namespace}/poddisruptionbudgets/{name}/status',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'get',
            $options
        );
    }

    /**
     * Partially update status of the specified PodDisruptionBudget
     *
     * Allowed query parameters:
     *   pretty
     *
     * @param array $query
     */
    public function patchNamespacedStatus(string $name, PatchInterface $patch, array $query = []): PodDisruptionBudget
    {
        $options['query'] = $query;
        $options['body'] = $patch;
        $options['model'] = PodDisruptionBudget::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/namespaces/{namespace}/poddisruptionbudgets/{name}/status',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'patch',
            $options
        );
    }

    /**
     * Replace status of the specified PodDisruptionBudget
     *
     * Allowed query parameters:
     *   pretty
     *
     * @param array $query
     */
    public function replaceNamespacedStatus(string $name, PodDisruptionBudget $podDisruptionBudget, array $query = []): PodDisruptionBudget
    {
        $options['query'] = $query;
        $options['body'] = $podDisruptionBudget;
        $options['model'] = PodDisruptionBudget::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/namespaces/{namespace}/poddisruptionbudgets/{name}/status',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'put',
            $options
        );
    }

    /**
     * List or watch objects of kind PodDisruptionBudget
     *
     * Allowed query parameters:
     *   continue
     *   fieldSelector
     *   includeUninitialized
     *   labelSelector
     *   limit
     *   pretty
     *   resourceVersion
     *   timeoutSeconds
     *   watch
     *
     * @param array $query
     * @param callable|object|null $handler
     */
    public function listForAllNamespaces(array $query = [], $handler = null): ?PodDisruptionBudgetList
    {
        $options['query'] = $query;
        $options['handler'] = $handler;
        $options['model'] = PodDisruptionBudgetList::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/poddisruptionbudgets',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'list',
            $options
        );
    }

    /**
     * Watch individual changes to a list of PodDisruptionBudget
     *
     * Allowed query parameters:
     *   continue
     *   fieldSelector
     *   includeUninitialized
     *   labelSelector
     *   limit
     *   pretty
     *   resourceVersion
     *   timeoutSeconds
     *   watch
     *
     * @param array $query
     * @param callable|object|null $handler
     */
    public function watchNamespacedList(array $query = [], $handler = null): void
    {
        $options['query'] = $query;
        $options['handler'] = $handler;
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/watch/namespaces/{namespace}/poddisruptionbudgets',
            [],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watchlist',
            $options
        );
    }

    /**
     * Watch changes to an object of kind PodDisruptionBudget
     *
     * Allowed query parameters:
     *   continue
     *   fieldSelector
     *   includeUninitialized
     *   labelSelector
     *   limit
     *   pretty
     *   resourceVersion
     *   timeoutSeconds
     *   watch
     *
     * @param array $query
     * @param callable|object|null $handler
     */
    public function watchNamespaced(string $name, array $query = [], $handler = null): void
    {
        $options['query'] = $query;
        $options['handler'] = $handler;
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/watch/namespaces/{namespace}/poddisruptionbudgets/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watch',
            $options
        );
    }

    /**
     * Watch individual changes to a list of PodDisruptionBudget
     *
     * Allowed query parameters:
     *   continue
     *   fieldSelector
     *   includeUninitialized
     *   labelSelector
     *   limit
     *   pretty
     *   resourceVersion
     *   timeoutSeconds
     *   watch
     *
     * @param array $query
     * @param callable|object|null $handler
     */
    public function watchListForAllNamespaces(array $query = [], $handler = null): void
    {
        $options['query'] = $query;
        $options['handler'] = $handler;
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/policy/v1beta1/watch/poddisruptionbudgets',
            [],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watchlist',
            $options
        );
    }
}
