<?php

/**
 * This file was automatically generated by k8s/api-generator 0.12.0 for API version v1.28.11
 *
 * (c) Chad Sikorra <Chad.Sikorra@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace K8s\Api\Service\Storage\v1;

use K8s\Api\Model\Api\Storage\v1\CSINode;
use K8s\Api\Model\Api\Storage\v1\CSINodeList;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\Status;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\WatchEvent;
use K8s\Core\Contract\ApiInterface;

class CSINodeService
{
    /** @var ApiInterface */
    private $api;

    /** @var string|null */
    private $namespace;

    public function __construct(ApiInterface $api)
    {
        $this->api = $api;
    }

    public function useNamespace(string $namespace): self
    {
        $this->namespace = $namespace;

        return $this;
    }

    /**
     * List or watch objects of kind CSINode
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#list-csinode-v1-storage-k8s-io
     */
    public function listStorageV1(array $query = []): CSINodeList
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = CSINodeList::class;
        $uri = $this->api->makeUri(
            '/apis/storage.k8s.io/v1/csinodes',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'list',
            $options
        );
    }

    /**
     * Delete collection of CSINode
     *
     * Allowed query parameters:
     *   dryRun
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#delete-collection-csinode-v1-storage-k8s-io
     */
    public function deleteStorageV1Collection(array $query = []): Status
    {
        $options['query'] = $query;
        $options['method'] = 'delete';
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/apis/storage.k8s.io/v1/csinodes',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'deletecollection',
            $options
        );
    }

    /**
     * Create a CSINode
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#create-csinode-v1-storage-k8s-io
     */
    public function createStorageV1(CSINode $cSINode, array $query = []): CSINode
    {
        $options['query'] = $query;
        $options['method'] = 'post';
        $options['body'] = $cSINode;
        $options['model'] = CSINode::class;
        $uri = $this->api->makeUri(
            '/apis/storage.k8s.io/v1/csinodes',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'post',
            $options
        );
    }

    /**
     * Read the specified CSINode
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#read-csinode-v1-storage-k8s-io
     */
    public function readStorageV1(string $name, array $query = []): CSINode
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = CSINode::class;
        $uri = $this->api->makeUri(
            '/apis/storage.k8s.io/v1/csinodes/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'get',
            $options
        );
    }

    /**
     * Delete a CSINode
     *
     * Allowed query parameters:
     *   dryRun
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#delete-csinode-v1-storage-k8s-io
     */
    public function deleteStorageV1(string $name, array $query = []): CSINode
    {
        $options['query'] = $query;
        $options['method'] = 'delete';
        $options['model'] = CSINode::class;
        $uri = $this->api->makeUri(
            '/apis/storage.k8s.io/v1/csinodes/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'delete',
            $options
        );
    }

    /**
     * Partially update the specified CSINode
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#patch-csinode-v1-storage-k8s-io
     */
    public function patchStorageV1(string $name, array $query = []): CSINode
    {
        $options['query'] = $query;
        $options['method'] = 'patch';
        $options['model'] = CSINode::class;
        $uri = $this->api->makeUri(
            '/apis/storage.k8s.io/v1/csinodes/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'patch',
            $options
        );
    }

    /**
     * Replace the specified CSINode
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#put-csinode-v1-storage-k8s-io
     */
    public function replaceStorageV1(string $name, CSINode $cSINode, array $query = []): CSINode
    {
        $options['query'] = $query;
        $options['method'] = 'put';
        $options['body'] = $cSINode;
        $options['model'] = CSINode::class;
        $uri = $this->api->makeUri(
            '/apis/storage.k8s.io/v1/csinodes/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'put',
            $options
        );
    }

    /**
     * Watch individual changes to a list of CSINode. deprecated: use the 'watch' parameter with a list
     * operation instead.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#watchlist-csinode-v1-storage-k8s-io
     */
    public function watchStorageV1List(array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/storage.k8s.io/v1/watch/csinodes',
            [],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watchlist',
            $options
        );
    }

    /**
     * Watch changes to an object of kind CSINode. deprecated: use the 'watch' parameter with a list
     * operation instead, filtered to a single item with the 'fieldSelector' parameter.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#watch-csinode-v1-storage-k8s-io
     */
    public function watchStorageV1(string $name, array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/storage.k8s.io/v1/watch/csinodes/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watch',
            $options
        );
    }
}
