<?php

/**
 * This file was automatically generated by k8s/api-generator 0.12.0 for API version v1.28.11
 *
 * (c) Chad Sikorra <Chad.Sikorra@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace K8s\Api\Service\Events\v1;

use K8s\Api\Model\Api\Events\v1\Event;
use K8s\Api\Model\Api\Events\v1\EventList;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\Status;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\WatchEvent;
use K8s\Core\Contract\ApiInterface;

class EventService
{
    /** @var ApiInterface */
    private $api;

    /** @var string|null */
    private $namespace;

    public function __construct(ApiInterface $api)
    {
        $this->api = $api;
    }

    public function useNamespace(string $namespace): self
    {
        $this->namespace = $namespace;

        return $this;
    }

    /**
     * List or watch objects of kind Event
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#list-event-v1-events-k8s-io
     */
    public function listsV1ForAllNamespaces(array $query = []): EventList
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = EventList::class;
        $uri = $this->api->makeUri(
            '/apis/events.k8s.io/v1/events',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'list',
            $options
        );
    }

    /**
     * List or watch objects of kind Event
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#list-event-v1-events-k8s-io
     */
    public function listsV1Namespaced(array $query = []): EventList
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = EventList::class;
        $uri = $this->api->makeUri(
            '/apis/events.k8s.io/v1/namespaces/{namespace}/events',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'list',
            $options
        );
    }

    /**
     * Delete collection of Event
     *
     * Allowed query parameters:
     *   dryRun
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#delete-collection-event-v1-events-k8s-io
     */
    public function deletesV1CollectionNamespaced(array $query = []): Status
    {
        $options['query'] = $query;
        $options['method'] = 'delete';
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/apis/events.k8s.io/v1/namespaces/{namespace}/events',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'deletecollection',
            $options
        );
    }

    /**
     * Create an Event
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#create-event-v1-events-k8s-io
     */
    public function createsV1Namespaced(Event $event, array $query = []): Event
    {
        $options['query'] = $query;
        $options['method'] = 'post';
        $options['body'] = $event;
        $options['model'] = Event::class;
        $uri = $this->api->makeUri(
            '/apis/events.k8s.io/v1/namespaces/{namespace}/events',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'post',
            $options
        );
    }

    /**
     * Read the specified Event
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#read-event-v1-events-k8s-io
     */
    public function readsV1Namespaced(string $name, array $query = []): Event
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = Event::class;
        $uri = $this->api->makeUri(
            '/apis/events.k8s.io/v1/namespaces/{namespace}/events/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'get',
            $options
        );
    }

    /**
     * Delete an Event
     *
     * Allowed query parameters:
     *   dryRun
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#delete-event-v1-events-k8s-io
     */
    public function deletesV1Namespaced(string $name, array $query = []): Status
    {
        $options['query'] = $query;
        $options['method'] = 'delete';
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/apis/events.k8s.io/v1/namespaces/{namespace}/events/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'delete',
            $options
        );
    }

    /**
     * Partially update the specified Event
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#patch-event-v1-events-k8s-io
     */
    public function patchsV1Namespaced(string $name, array $query = []): Event
    {
        $options['query'] = $query;
        $options['method'] = 'patch';
        $options['model'] = Event::class;
        $uri = $this->api->makeUri(
            '/apis/events.k8s.io/v1/namespaces/{namespace}/events/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'patch',
            $options
        );
    }

    /**
     * Replace the specified Event
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#put-event-v1-events-k8s-io
     */
    public function replacesV1Namespaced(string $name, Event $event, array $query = []): Event
    {
        $options['query'] = $query;
        $options['method'] = 'put';
        $options['body'] = $event;
        $options['model'] = Event::class;
        $uri = $this->api->makeUri(
            '/apis/events.k8s.io/v1/namespaces/{namespace}/events/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'put',
            $options
        );
    }

    /**
     * Watch individual changes to a list of Event. deprecated: use the 'watch' parameter with a list
     * operation instead.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#watchlist-event-v1-events-k8s-io
     */
    public function watchsV1ListForAllNamespaces(array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/events.k8s.io/v1/watch/events',
            [],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watchlist',
            $options
        );
    }

    /**
     * Watch individual changes to a list of Event. deprecated: use the 'watch' parameter with a list
     * operation instead.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#watchlist-event-v1-events-k8s-io
     */
    public function watchsV1NamespacedList(array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/events.k8s.io/v1/watch/namespaces/{namespace}/events',
            [],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watchlist',
            $options
        );
    }

    /**
     * Watch changes to an object of kind Event. deprecated: use the 'watch' parameter with a list
     * operation instead, filtered to a single item with the 'fieldSelector' parameter.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#watch-event-v1-events-k8s-io
     */
    public function watchsV1Namespaced(string $name, array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/events.k8s.io/v1/watch/namespaces/{namespace}/events/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watch',
            $options
        );
    }
}
