<?php

/**
 * This file was automatically generated by k8s/api-generator 0.12.0 for API version v1.27.15
 *
 * (c) Chad Sikorra <Chad.Sikorra@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace K8s\Api\Service\AdmissionRegistration\v1alpha1;

use K8s\Api\Model\Api\AdmissionRegistration\v1alpha1\ValidatingAdmissionPolicyBinding;
use K8s\Api\Model\Api\AdmissionRegistration\v1alpha1\ValidatingAdmissionPolicyBindingList;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\Status;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\WatchEvent;
use K8s\Core\Contract\ApiInterface;
use K8s\Core\PatchInterface;

class ValidatingAdmissionPolicyBindingService
{
    /** @var ApiInterface */
    private $api;

    /** @var string|null */
    private $namespace;

    public function __construct(ApiInterface $api)
    {
        $this->api = $api;
    }

    public function useNamespace(string $namespace): self
    {
        $this->namespace = $namespace;

        return $this;
    }

    /**
     * List or watch objects of kind ValidatingAdmissionPolicyBinding
     *
     * Allowed query parameters:
     *   allowWatchBookmarks
     *   continue
     *   fieldSelector
     *   labelSelector
     *   limit
     *   resourceVersion
     *   resourceVersionMatch
     *   sendInitialEvents
     *   timeoutSeconds
     *   watch
     *   pretty
     *
     * @param array $query
     * @param callable|object|null $handler
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#list-validatingadmissionpolicybinding-v1alpha1-admissionregistration-k8s-io
     */
    public function listAdmissionRegistrationV1alpha1(array $query = [], $handler = null): ?ValidatingAdmissionPolicyBindingList
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['handler'] = $handler;
        $options['model'] = ValidatingAdmissionPolicyBindingList::class;
        $uri = $this->api->makeUri(
            '/apis/admissionregistration.k8s.io/v1alpha1/validatingadmissionpolicybindings',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'list',
            $options
        );
    }

    /**
     * Delete collection of ValidatingAdmissionPolicyBinding
     *
     * Allowed query parameters:
     *   continue
     *   dryRun
     *   fieldSelector
     *   gracePeriodSeconds
     *   labelSelector
     *   limit
     *   orphanDependents
     *   propagationPolicy
     *   resourceVersion
     *   resourceVersionMatch
     *   sendInitialEvents
     *   timeoutSeconds
     *   pretty
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#delete-collection-validatingadmissionpolicybinding-v1alpha1-admissionregistration-k8s-io
     */
    public function deleteAdmissionRegistrationV1alpha1Collection(array $query = []): Status
    {
        $options['query'] = $query;
        $options['method'] = 'delete';
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/apis/admissionregistration.k8s.io/v1alpha1/validatingadmissionpolicybindings',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'deletecollection',
            $options
        );
    }

    /**
     * Create a ValidatingAdmissionPolicyBinding
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldManager
     *   fieldValidation
     *   pretty
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#create-validatingadmissionpolicybinding-v1alpha1-admissionregistration-k8s-io
     */
    public function createAdmissionRegistrationV1alpha1(ValidatingAdmissionPolicyBinding $validatingAdmissionPolicyBinding, array $query = []): ValidatingAdmissionPolicyBinding
    {
        $options['query'] = $query;
        $options['method'] = 'post';
        $options['body'] = $validatingAdmissionPolicyBinding;
        $options['model'] = ValidatingAdmissionPolicyBinding::class;
        $uri = $this->api->makeUri(
            '/apis/admissionregistration.k8s.io/v1alpha1/validatingadmissionpolicybindings',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'post',
            $options
        );
    }

    /**
     * Read the specified ValidatingAdmissionPolicyBinding
     *
     * Allowed query parameters:
     *   pretty
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#read-validatingadmissionpolicybinding-v1alpha1-admissionregistration-k8s-io
     */
    public function readAdmissionRegistrationV1alpha1(string $name, array $query = []): ValidatingAdmissionPolicyBinding
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = ValidatingAdmissionPolicyBinding::class;
        $uri = $this->api->makeUri(
            '/apis/admissionregistration.k8s.io/v1alpha1/validatingadmissionpolicybindings/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'get',
            $options
        );
    }

    /**
     * Delete a ValidatingAdmissionPolicyBinding
     *
     * Allowed query parameters:
     *   dryRun
     *   gracePeriodSeconds
     *   orphanDependents
     *   propagationPolicy
     *   pretty
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#delete-validatingadmissionpolicybinding-v1alpha1-admissionregistration-k8s-io
     */
    public function deleteAdmissionRegistrationV1alpha1(string $name, array $query = []): Status
    {
        $options['query'] = $query;
        $options['method'] = 'delete';
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/apis/admissionregistration.k8s.io/v1alpha1/validatingadmissionpolicybindings/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'delete',
            $options
        );
    }

    /**
     * Partially update the specified ValidatingAdmissionPolicyBinding
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldManager
     *   fieldValidation
     *   force
     *   pretty
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#patch-validatingadmissionpolicybinding-v1alpha1-admissionregistration-k8s-io
     */
    public function patchAdmissionRegistrationV1alpha1(string $name, PatchInterface $patch, array $query = []): ValidatingAdmissionPolicyBinding
    {
        $options['query'] = $query;
        $options['method'] = 'patch';
        $options['body'] = $patch;
        $options['model'] = ValidatingAdmissionPolicyBinding::class;
        $uri = $this->api->makeUri(
            '/apis/admissionregistration.k8s.io/v1alpha1/validatingadmissionpolicybindings/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'patch',
            $options
        );
    }

    /**
     * Replace the specified ValidatingAdmissionPolicyBinding
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldManager
     *   fieldValidation
     *   pretty
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#put-validatingadmissionpolicybinding-v1alpha1-admissionregistration-k8s-io
     */
    public function replaceAdmissionRegistrationV1alpha1(string $name, ValidatingAdmissionPolicyBinding $validatingAdmissionPolicyBinding, array $query = []): ValidatingAdmissionPolicyBinding
    {
        $options['query'] = $query;
        $options['method'] = 'put';
        $options['body'] = $validatingAdmissionPolicyBinding;
        $options['model'] = ValidatingAdmissionPolicyBinding::class;
        $uri = $this->api->makeUri(
            '/apis/admissionregistration.k8s.io/v1alpha1/validatingadmissionpolicybindings/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'put',
            $options
        );
    }

    /**
     * Watch individual changes to a list of ValidatingAdmissionPolicyBinding. deprecated: use the 'watch'
     * parameter with a list operation instead.
     *
     * Allowed query parameters:
     *   allowWatchBookmarks
     *   continue
     *   fieldSelector
     *   labelSelector
     *   limit
     *   pretty
     *   resourceVersion
     *   resourceVersionMatch
     *   sendInitialEvents
     *   timeoutSeconds
     *   watch
     *
     * @param array $query
     * @param callable|object|null $handler
     * @deprecated Use the 'watch' parameter with a list operation instead.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#watchlist-validatingadmissionpolicybinding-v1alpha1-admissionregistration-k8s-io
     */
    public function watchAdmissionRegistrationV1alpha1List(array $query = [], $handler = null): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['handler'] = $handler;
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/admissionregistration.k8s.io/v1alpha1/watch/validatingadmissionpolicybindings',
            [],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watchlist',
            $options
        );
    }

    /**
     * Watch changes to an object of kind ValidatingAdmissionPolicyBinding. deprecated: use the 'watch'
     * parameter with a list operation instead, filtered to a single item with the 'fieldSelector'
     * parameter.
     *
     * Allowed query parameters:
     *   allowWatchBookmarks
     *   continue
     *   fieldSelector
     *   labelSelector
     *   limit
     *   pretty
     *   resourceVersion
     *   resourceVersionMatch
     *   sendInitialEvents
     *   timeoutSeconds
     *   watch
     *
     * @param array $query
     * @param callable|object|null $handler
     * @deprecated Use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#watch-validatingadmissionpolicybinding-v1alpha1-admissionregistration-k8s-io
     */
    public function watchAdmissionRegistrationV1alpha1(string $name, array $query = [], $handler = null): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['handler'] = $handler;
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/apis/admissionregistration.k8s.io/v1alpha1/watch/validatingadmissionpolicybindings/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watch',
            $options
        );
    }
}
