<?php

/**
 * This file was automatically generated by k8s/api-generator 0.12.0 for API version v1.30.2
 *
 * (c) Chad Sikorra <Chad.Sikorra@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace K8s\Api\Service\Core\v1;

use K8s\Api\Model\Api\Core\v1\K8sNamespace;
use K8s\Api\Model\Api\Core\v1\NamespaceList;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\Status;
use K8s\Api\Model\ApiMachinery\Apis\Meta\v1\WatchEvent;
use K8s\Core\Contract\ApiInterface;

/**
 * Namespace provides a scope for Names. Use of multiple namespaces is optional.
 */
class NamespaceService
{
    /** @var ApiInterface */
    private $api;

    /** @var string|null */
    private $namespace;

    public function __construct(ApiInterface $api)
    {
        $this->api = $api;
    }

    public function useNamespace(string $namespace): self
    {
        $this->namespace = $namespace;

        return $this;
    }

    /**
     * List or watch objects of kind Namespace
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#list-namespace-v1-core
     */
    public function list(array $query = []): NamespaceList
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = NamespaceList::class;
        $uri = $this->api->makeUri(
            '/api/v1/namespaces',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'list',
            $options
        );
    }

    /**
     * Create a Namespace
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#create-namespace-v1-core
     */
    public function create(K8sNamespace $k8sNamespace, array $query = []): K8sNamespace
    {
        $options['query'] = $query;
        $options['method'] = 'post';
        $options['body'] = $k8sNamespace;
        $options['model'] = K8sNamespace::class;
        $uri = $this->api->makeUri(
            '/api/v1/namespaces',
            [],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'post',
            $options
        );
    }

    /**
     * Read the specified Namespace
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#read-namespace-v1-core
     */
    public function read(string $name, array $query = []): K8sNamespace
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = K8sNamespace::class;
        $uri = $this->api->makeUri(
            '/api/v1/namespaces/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'get',
            $options
        );
    }

    /**
     * Delete a Namespace
     *
     * Allowed query parameters:
     *   dryRun
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#delete-namespace-v1-core
     */
    public function delete(string $name, array $query = []): Status
    {
        $options['query'] = $query;
        $options['method'] = 'delete';
        $options['model'] = Status::class;
        $uri = $this->api->makeUri(
            '/api/v1/namespaces/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'delete',
            $options
        );
    }

    /**
     * Partially update the specified Namespace
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#patch-namespace-v1-core
     */
    public function patch(string $name, array $query = []): K8sNamespace
    {
        $options['query'] = $query;
        $options['method'] = 'patch';
        $options['model'] = K8sNamespace::class;
        $uri = $this->api->makeUri(
            '/api/v1/namespaces/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'patch',
            $options
        );
    }

    /**
     * Replace the specified Namespace
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#put-namespace-v1-core
     */
    public function replace(string $name, K8sNamespace $k8sNamespace, array $query = []): K8sNamespace
    {
        $options['query'] = $query;
        $options['method'] = 'put';
        $options['body'] = $k8sNamespace;
        $options['model'] = K8sNamespace::class;
        $uri = $this->api->makeUri(
            '/api/v1/namespaces/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'put',
            $options
        );
    }

    /**
     * Replace finalize of the specified Namespace
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#put-namespace-v1-core
     */
    public function replaceFinalize(string $name, K8sNamespace $k8sNamespace, array $query = []): K8sNamespace
    {
        $options['query'] = $query;
        $options['method'] = 'put';
        $options['body'] = $k8sNamespace;
        $options['model'] = K8sNamespace::class;
        $uri = $this->api->makeUri(
            '/api/v1/namespaces/{name}/finalize',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'put',
            $options
        );
    }

    /**
     * Read status of the specified Namespace
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#read-namespace-v1-core
     */
    public function readStatus(string $name, array $query = []): K8sNamespace
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = K8sNamespace::class;
        $uri = $this->api->makeUri(
            '/api/v1/namespaces/{name}/status',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'get',
            $options
        );
    }

    /**
     * Partially update status of the specified Namespace
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#patch-namespace-v1-core
     */
    public function patchStatus(string $name, array $query = []): K8sNamespace
    {
        $options['query'] = $query;
        $options['method'] = 'patch';
        $options['model'] = K8sNamespace::class;
        $uri = $this->api->makeUri(
            '/api/v1/namespaces/{name}/status',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'patch',
            $options
        );
    }

    /**
     * Replace status of the specified Namespace
     *
     * Allowed query parameters:
     *   dryRun
     *   fieldValidation
     *
     * @param array $query
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#put-namespace-v1-core
     */
    public function replaceStatus(string $name, K8sNamespace $k8sNamespace, array $query = []): K8sNamespace
    {
        $options['query'] = $query;
        $options['method'] = 'put';
        $options['body'] = $k8sNamespace;
        $options['model'] = K8sNamespace::class;
        $uri = $this->api->makeUri(
            '/api/v1/namespaces/{name}/status',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        return $this->api->executeHttp(
            $uri,
            'put',
            $options
        );
    }

    /**
     * Watch individual changes to a list of Namespace. deprecated: use the 'watch' parameter with a list
     * operation instead.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#watchlist-namespace-v1-core
     */
    public function watchList(array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/api/v1/watch/namespaces',
            [],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watchlist',
            $options
        );
    }

    /**
     * Watch changes to an object of kind Namespace. deprecated: use the 'watch' parameter with a list
     * operation instead, filtered to a single item with the 'fieldSelector' parameter.
     *
     * @param array $query
     * @deprecated Use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
     * @link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#watch-namespace-v1-core
     */
    public function watch(string $name, array $query = []): void
    {
        $options['query'] = $query;
        $options['method'] = 'get';
        $options['model'] = WatchEvent::class;
        $uri = $this->api->makeUri(
            '/api/v1/watch/namespaces/{name}',
            ['{name}' => $name,],
            $query,
            $this->namespace
        );

        $this->api->executeHttp(
            $uri,
            'watch',
            $options
        );
    }
}
