<?php

/**
 * This file was automatically generated by k8s/api-generator 0.12.0 for API version v1.30.2
 *
 * (c) Chad Sikorra <Chad.Sikorra@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace K8s\Api\Model\Api\Resource\v1alpha2;

use K8s\Core\Annotation as Kubernetes;

/**
 * DriverAllocationResult contains vendor parameters and the allocation result for one request.
 */
class DriverAllocationResult
{
    /**
     * @Kubernetes\Attribute("namedResources",type="model",model=NamedResourcesAllocationResult::class)
     * @var NamedResourcesAllocationResult|null
     */
    protected $namedResources = null;

    /**
     * @Kubernetes\Attribute("vendorRequestParameters")
     * @var object|null
     */
    protected $vendorRequestParameters = null;

    /**
     * @param NamedResourcesAllocationResult|null $namedResources
     * @param object|null $vendorRequestParameters
     */
    public function __construct(?NamedResourcesAllocationResult $namedResources = null, $vendorRequestParameters = null)
    {
        $this->namedResources = $namedResources;
        $this->vendorRequestParameters = $vendorRequestParameters;
    }

    /**
     * NamedResources describes the allocation result when using the named resources model.
     */
    public function getNamedResources(): ?NamedResourcesAllocationResult
    {
        return $this->namedResources;
    }

    /**
     * NamedResources describes the allocation result when using the named resources model.
     *
     * @return static
     */
    public function setNamedResources(NamedResourcesAllocationResult $namedResources)
    {
        $this->namedResources = $namedResources;

        return $this;
    }

    /**
     * VendorRequestParameters are the per-request configuration parameters from the time that the claim
     * was allocated.
     *
     * @return object
     */
    public function getVendorRequestParameters()
    {
        return $this->vendorRequestParameters;
    }

    /**
     * VendorRequestParameters are the per-request configuration parameters from the time that the claim
     * was allocated.
     *
     * @param object $vendorRequestParameters
     * @return static
     */
    public function setVendorRequestParameters($vendorRequestParameters)
    {
        $this->vendorRequestParameters = $vendorRequestParameters;

        return $this;
    }
}
