<?php

/**
 * This file was automatically generated by k8s/api-generator 0.12.0 for API version v1.28.11
 *
 * (c) Chad Sikorra <Chad.Sikorra@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace K8s\Api\Model\Api\Resource\v1alpha2;

use K8s\Core\Annotation as Kubernetes;

/**
 * ResourceHandle holds opaque resource data for processing by a specific kubelet plugin.
 */
class ResourceHandle
{
    /**
     * @Kubernetes\Attribute("data")
     * @var string|null
     */
    protected $data = null;

    /**
     * @Kubernetes\Attribute("driverName")
     * @var string|null
     */
    protected $driverName = null;

    /**
     * @param string|null $data
     * @param string|null $driverName
     */
    public function __construct(?string $data = null, ?string $driverName = null)
    {
        $this->data = $data;
        $this->driverName = $driverName;
    }

    /**
     * Data contains the opaque data associated with this ResourceHandle. It is set by the controller
     * component of the resource driver whose name matches the DriverName set in the ResourceClaimStatus
     * this ResourceHandle is embedded in. It is set at allocation time and is intended for processing by
     * the kubelet plugin whose name matches the DriverName set in this ResourceHandle.
     *
     * The maximum size of this field is 16KiB. This may get increased in the future, but not reduced.
     */
    public function getData(): ?string
    {
        return $this->data;
    }

    /**
     * Data contains the opaque data associated with this ResourceHandle. It is set by the controller
     * component of the resource driver whose name matches the DriverName set in the ResourceClaimStatus
     * this ResourceHandle is embedded in. It is set at allocation time and is intended for processing by
     * the kubelet plugin whose name matches the DriverName set in this ResourceHandle.
     *
     * The maximum size of this field is 16KiB. This may get increased in the future, but not reduced.
     *
     * @return static
     */
    public function setData(string $data)
    {
        $this->data = $data;

        return $this;
    }

    /**
     * DriverName specifies the name of the resource driver whose kubelet plugin should be invoked to
     * process this ResourceHandle's data once it lands on a node. This may differ from the DriverName set
     * in ResourceClaimStatus this ResourceHandle is embedded in.
     */
    public function getDriverName(): ?string
    {
        return $this->driverName;
    }

    /**
     * DriverName specifies the name of the resource driver whose kubelet plugin should be invoked to
     * process this ResourceHandle's data once it lands on a node. This may differ from the DriverName set
     * in ResourceClaimStatus this ResourceHandle is embedded in.
     *
     * @return static
     */
    public function setDriverName(string $driverName)
    {
        $this->driverName = $driverName;

        return $this;
    }
}
